GET http://localhost:9080/Shipyard/api/ships
Accept: application/json

###

GET http://localhost:9080/Shipyard/api/harbors/AMS/ships/1
Accept: application/json

###

GET http://localhost:9080/Shipyard/api/harbors/AMS/ships/2
Accept: application/json

###